# -*- coding: utf-8 -*-
"""PYTHON ASSINGNMENT 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kx78wCskCNEVBF3GibpPWpjqHHsXY6SA

ASSINGNMENT
"""

#even or odd(1)
text=int(input('enter the number:'))

if (text%2)==0:
  print('its an even number')
else:
  print('its an odd number')

#+,-,0(2)
x=int(input('enter the number'))

if x>0:
  print('positive')
elif x<0:
  print('negative')
else:
  print('zero')

#divisibility(3)
text=int(input('enter the number'))

if text%3==0 and text%5==0:
  print('the number is divisible by 3 or 5')
else:
  print('the number is not divisible by 3 or 5')

#temperaturte(4)
x=int(input('enter the number'))

if x>30:
  print('hot')
else:
  print('cool')

#pass or fail(5)
x=int(input('enter the number'))

if x>=100:
  print('pass')
else:
  print('fail')

#greatest of 2 numbers(6)
x=int(input('enter the number:'))
y=int(input('enter the number:'))
text='{}'
if x==y:
  print(f'{x} equal to {y}')
elif x>y:
  print(text.format(x),'is the greter than',text.format(y))
elif x<y:
  print(text.format(y),'is the greter than',text.format(x))
else:
  print("both are equal")

#greatest of three numbers(7)
x=int(input('enter the number:'))
y=int(input('enter the number:'))
z=int(input('enter the number:'))

if x==y==z:
  print('they are equal')
elif x>y:
  if x>z:
    print(f'{x} is the greatest number')
  else :
    print(f"{z} is the greatest number")
elif y>z:
    print(f"{y} is the greatest number")
else:
    print(f"{z} is the greatest number")

#age group classifier(8)
x=int(input('enter the age:'))
if x<13:
  print('child')
elif 13<=x<20:
  print("teenager")
elif 20<=x<60:
  print('adult')
else:
  print('senior citizen')

#grade classification(9)
x=int(input('enter the grade:'))

if 0<=x<=100:
  if x>=90:
     print('A grade')
  elif x>=75:
     print('B grade')
  elif x>=50:
     print('C grade')
  else:
     print('fail')
else:
  print('enter mark between 0 to 100')

#temperature(10)
x=int(input('enter the temperature:'))
y=int(input('enter humidity:'))
if x>30 and y>70:
  print('too hot and humid')
elif x>30 and y<=70:
  print('hot but dry')
elif x<=30 and y>70:
  print('cool but humid')
else:
  print('pleasant weather')

#bmi(11)
x=int(input('enter height:'))
y=int(input('enter weight:'))
z=x/(y*y)
if z<18.5:
  print('underweight')
elif 18.5<z<24.9:
  print('normal')
elif 25<z<29.9:
  print('overweight')
else:
   print('obese')

#basic data validation(12)
x=float(input('enter a value:'))
if 0<=x<=1:
    print('valid probability')
else:
    print('invalid')

#rainfall(13)
x=int(input('enter a value mm:'))
if 0<=x<=100:
  if x>100:
    print('heavy rain')
  elif 50<x<100:
    print('moderate rain')
  else :
    print('light rain')
else:
  print('enter value under 100')

#number classsification(14)
x=int(input('enter the number:'))

if x%2==0 and x%3==0:
  print('divisible by both 2 and 3')
elif (x%2)==0:
  print('divisible by 2 only')
elif(x%3)==0:
  print('divisible by 3 only')
else:
  print('not divisible by 2 or 3')